### PR TITLE
Use detected chrome path as default

### LINKED ISSUE #739: chromedriver 115.0.5790.102 not working
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.15.4 (compiled with Erlang/OTP 26)

### Operating system

Mac OS 13

### Browser

Google Chrome 115.0.5790.102

### Driver

115.0.5790.102

### Correct Configuration

- I confirm that I have Wallaby configured correctly.

### Current behavior

Using Google Chrome and chromedriver `115.0.5790.102` I get the following error:

`{:error, "unknown error: cannot find Chrome binary\n  (Driver info: chromedriver=115.0.5790.102 (90efd4b0ad6aa15eeafcdabd5817ae939f7ba059-refs/branch-heads/5790_90@{#9}),platform=Mac OS X 13.4.1 arm64)"}`

Is anyone else encountering this problem? Maybe something has changed and we need to pass in the path to the Google Chrome location?  

### Expected behavior

I expect no error.

### Test Code & HTML

Install the latest Google Chrome and chromedriver.

`Wallaby.start_session`

results in 

`
{:error,
 "unknown error: cannot find Chrome binary\n  (Driver info: chromedriver=115.0.5790.102 (90efd4b0ad6aa15eeafcdabd5817ae939f7ba059-refs/branch-heads/5790_90@{#9}),platform=Mac OS X 13.4.1 arm64)"}
`

### Demonstration Project

_No response_

### PR DESCRIPTION
**Pull request by dvic**
Fixes #739

### CODE REVIEW

**Comment by dvic** [comment]
@mhanberg I just modified the `default_capabilities` and only setting the `binary` option if the detection was successful.

**Comment by dvic** [comment]
Oops :) This breaks some tests. Looking into it.

**Comment by dvic** [comment]
It seems like `System.find_executable` returns `google-chrome` and not a path, I tested this on my own repo (using github action ssh debug) and it should return 

```
iex(1)> System.find_executable("google-chrome")
"/usr/bin/google-chrome"
iex(2)> :os.type
{:unix, :linux}
```

**Comment by dvic** [comment]
Ok I think I found it 🤞: https://github.com/elixir-wallaby/wallaby/pull/740/commits/735952399bfaab04bd0b86a250ea759b8f92682d

**Comment by dvic** [comment]
🥳 it's fixed

**Comment by mhanberg** [comment]
i'll be able to take a closer look at this tonight, thanks!

**Pull request merged**
