### PR TITLE
Expand documentation for window related functions

### LINKED ISSUE #628: The `Wallaby.Session.t()` typespec is private
## Issue

The `Wallaby.Session.t()` typespec is private which causes issues.

We fail CI when the documentation raises warnings which occurs because the typespec is private.
```
warning: documentation references type "Wallaby.Session.t()" but it is hidden or private
```

I assume the spec is private as the details of the `Wallaby.Session` module should stay hidden but if there was a public `Wallaby.session()` typespec instead that could solve this problem.

### PR DESCRIPTION
**Pull request by mhanberg**
Also fixes #628

### CODE REVIEW

**Comment by mhanberg** [comment]
@rrrene really sorry to bother you, but do you have any idea why i'd be getting these Credo errors? https://github.com/elixir-wallaby/wallaby/pull/629/checks?check_run_id=3617265849

I am sort of at a loss 😅.

(Feel free to ignore this if you don't have free time. I wanted to avoid opening an issue as I can't imagine this is a bug in credo)

**Comment by rrrene** [comment]
@mhanberg It's a Credo bug. Thx for reporting this. Working on a minimal reproducible example.

**Comment by rrrene** [comment]
@mhanberg Thanks for reporting this 😀  It is now fixed on `master`.

Could you try this again by setting your Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by mhanberg** [comment]
@rrrene I opened another PR to trial the credo updates #630.

Looks like there are still a few false positives.

**Pull request merged**
