### PR TITLE
Update all dependencies and move to Elixir >= 1.14

### PR DESCRIPTION
**Pull request by pierrelegall**
I tried to use Wallaby in an Elixir `v1.15` & Phoenix `v1.7` project, then I noted Wallaby's dependencies are far from there last stable versions. So I updated them making the choice to set the Elixir version `>= 1.14`.

I saw the work of @kyleboe and @mhanberg too late, but I included some of their work in the PR.

### CODE REVIEW

**Comment by mhanberg** [comment]
were you unable to get wallaby working with the currently released dependency requirements?

**Comment by pierrelegall** [comment]
I finally got the same issue with both, fixed removing the `async: true` on `use ExUnit.Case` (even with only one feature test) :smiling_face_with_tear:

```
09:43:38.875 [error] GenServer #PID<0.1186.0> terminating
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.1186.0>.

When using ownership, you must manage connections in one
of the four ways:

* By explicitly checking out a connection
* By explicitly allowing a spawned process
* By running the pool in shared mode
* By using :caller option with allowed process

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

The fourth option requires [caller: pid] to be used when
checking out a connection from the pool. The caller process
should already be allowed on a connection.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.

See Ecto.Adapters.SQL.Sandbox docs for more information.
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1051: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
    (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (djo 0.1.0) lib/djo/services/searches_service.ex:22: Djo.Services.Searches.search/2
    (djo 0.1.0) lib/djo/services/searches_service.ex:30: Djo.Services.Searches.search/2
    (djo 0.1.0) lib/djo_web/live/search_live.ex:89: DjoWeb.Live.Search.assign_results/2
    (djo 0.1.0) lib/djo_web/live/search_live.ex:83: DjoWeb.Live.Search.handle_event/3
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/channel.ex:497: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 1.2.1) /home/pierre/Code/djo/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/channel.ex:250: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 5.2) gen_server.erl:1095: :gen_server.try_handle_info/3
    (stdlib 5.2) gen_server.erl:1183: :gen_server.handle_msg/6
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F6dm_EXRzFbpihvE", event: "event", payload: %{"event" => "search", "type" => "form", "uploads" => %{}, "value" => "query=Dwellearth&_target=query"}, ref: "8", join_ref: "4"}
```

**Comment by pierrelegall** [comment]
I still got issues making it working well with `phoenix_live_view` (`v0.20.3`).

**Comment by pierrelegall** [comment]
@mhanberg Are you ok to set Elixir `v1.14` as mininum dependency for the next Wallaby versions?

**Comment by mhanberg** [comment]
@pierrelegall bump on this question

> were you unable to get wallaby working with the currently released dependency requirements?

**Comment by pierrelegall** [comment]
> I finally got the same issue with both

Sorry if I wasn't clear: it was my answer for "Yes, I finally make it works with the currently released dependency requirements".

**Comment by mhanberg** [comment]
gotcha, so there is no need for this PR? i'd rather not update the deps and increase the required elixir if its not causing a problem.

i assume the ecto error you have above is related to #757

**Comment by pierrelegall** [comment]
I understand the choice.

I can try to set back minimum Elixir version requirement to Elixir `v1.12` with the updated dependencies and tests fixes of this PR soon.

**Comment by mhanberg** [comment]
Sorry, I meant that if there isn't any trouble with dependency resolution, then we don't need to update any of the dependencies.

**Pull request closed without merging**
