### PR TITLE
Create ChromeDriver Serverpool

### PR DESCRIPTION
**Pull request by paulz**
To address https://github.com/elixir-wallaby/wallaby/issues/365

From @aarongraham fork, see discussion:
https://github.com/elixir-wallaby/wallaby/issues/365#issuecomment-619453109

### CODE REVIEW

**Comment by michallepicki** [comment]
@mhanberg Do you think this PR needs to be resurrected in any form? I think it may have been closed by mistake when changing the project's default branch name, and it's being referrenced as a potential fix for the chromedriver concurrency bottleneck on the [TDD Phoenix Troubleshooting page](https://www.tddphoenix.com/troubleshooting/)

**Comment by mhanberg** [comment]
@michallepicki I'm not entirely sure, but I'm leaning towards no (it doesn't need to be resurrected.) But I'll investigate further.

**Comment by AndroidOatmeal** [comment]
Hey @mhanberg, did you get a chance to review whether this branch needs resurrecting? I'm still experiencing the RuntimeErrors described in https://github.com/elixir-wallaby/wallaby/issues/365, and thus far, this branch was the only fix for that problem I've found yet.

**Comment by mhanberg** [comment]
@AndroidOatmeal I have not.

Would you mind trying out [this](https://github.com/elixir-wallaby/wallaby/tree/finch2) branch? I was helping out someone else recently and that branch was able to get everything working for them. (They were running into the amorphous "httpoison error")

**Pull request closed without merging**
