### PR TITLE
Change Wallaby.Browser.sync_result from opaque to type

### LINKED ISSUE #539: "Attempted to pattern match against the internal structure of an opaque term"
The code
```elixir
    assert_has(session, css("h1", text: "Welcome!"))
```
in projects using Wallaby gives the dialyzer warning:
```
Attempted to pattern match against the internal structure of an opaque term.

Type:
Wallaby.Browser.sync_result()

Pattern:
{:ok, _}

This breaks the opaqueness of the term.
```
on Elixir 1.10.2/Erlang 22.3.1

Changing `Wallaby.Browser.sync_result` from `@opaque` to `@type` resolves this. PR incoming.

### PR DESCRIPTION
**Pull request by TheFirstAvenger**
Fixes #539.

Changes Wallaby.Browser.sync_result from `@opaque` to `@type`.

### CODE REVIEW

**Comment by mhanberg** [comment]
Thanks for the PR!

I am curious as to why dialyzer doesn't complain about this in the Wallaby codebase 🤔.

**Comment by TheFirstAvenger** [comment]
> I am curious as to why dialyzer doesn't complain about this in the Wallaby codebase 🤔.

From what I can see, `assert_has` is never called in compiled code in the Wallaby codebase, only in tests.

**Comment by mhanberg** [comment]
Ohh, that makes sense!

**Comment by mhanberg** [comment]
Do you mind also adding this change to the changelog?

**Comment by TheFirstAvenger** [comment]
> Do you mind also adding this change to the changelog?

Done

**Comment by mhanberg** [comment]
v0.26.1 has been released with this change.

Thanks for the contribution!

**Pull request merged**
