### PR TITLE
Update ex_doc and fix readme link

### LINKED ISSUE #701: Bug in hexdocs, readme link/expand button not visible
Not sure what's going on but https://hexdocs.pm/wallaby/api-reference.html#content

It seems that the readme doesn't have a title

image

### PR DESCRIPTION
**Pull request by dvic**
Fixes #701

### CODE REVIEW

**Comment by dvic** [comment]
Looks much better now :) 

image

**Comment by mhanberg** [comment]
actually while you're in here doing docs changes, would you mind doing `@moduledoc false` to the vendored PartitionSupervisor module? you can just delete the whole module doc and replace with `@moduledoc false`.

**Comment by dvic** [comment]
Done!

**Comment by mhanberg** [comment]
can you add the "```" to fix this error 
image

**Comment by dvic** [comment]
> can you add the "```" to fix this error
> image

Done :)

**Comment by mhanberg** [comment]
thanks!

**Pull request merged**
